/*

//JAVASCRIPT

ES UN LENGUAJE DE PROGRAMACION INTERPRETADO, DIALECTICO
DEL ESTANDAR ECMASCRIPT, SE DEFINE COMO ORIENTADO A OBJETOS,
BASADO EN PROTOTIPOS, IMPERATIVO, DEBILMENTE TIPADO Y DINAMICO.

//LENGUAJE DE PROGRAMACION INTERPRETADO

ES UN LENGUAJE DE PROGRAMACION PARA EL QUE LAS MAYORIAS DE SUS
IMPLEMENTACIONES EJECUTA LAS INSTRUCCIONES DIRECTAMENTE SIN PREVIA COMPILACION
DEL PROGRAMA A INSTRUCCIONES EN LENGUAJE MAQUINA.
ESTO QUIERE DECIR QUE EL INTERPRETE EJECUTA EL PROGRAMA
DIRECTAMENTE, TRADUCIENDO CADA SENTENCIA EN UNA SECUENCIA DE UNA O MAS
SUB-RUTINAS YA COMPILADAS EN EL CODIGO MAQUINA.

//PROGRAMACION BASADA EN PROTOTIPOS

ES UN ESTILO DE PROGRAMACION ORIENTADA A OBJETOS EN EL CUAL LOS OBJETOS NO SON
CREADOS MEDIANTE LA INSTANCIACION DE CLASES SINO MEDIANTE LA CLONACION DE OTROS
OBJETOS O MEDIANTE LA ESCRITURA DE CODIGO POR PARTE DEL PROGRAMADOR.
DE ESTA FORMA LOS OBJETOS YA EXISTENTES PUEDEN SERVIR DE PROTOTIPOS PARA LOS
QUE EL PROGRAMADOR NECESITE CREAR.

*UN PROTOTIPO DEFINIDO EN SU CODIGO FUENTE ES MUTABLE.
*ES EN SI MISMO UN OBJETO, ASI COMO OTROS.
*TIENE UNA EXISTENCIA FISICA EN LA MEMORIA.
*PUEDE SER MODIFICADO Y LLAMADO.
*DEBE SER NOMBRADO.
*PUEDE SER VISTO COMO UN MODELO EJEMPLAR EN UNA FAMILIA DE OBJETOS.
*UN OBJETO HEREDA PROPIEDADES(VALORES Y METODOS) DE SU PROTOTIPO.

//STANDAR ECMASCRIPT

ES UNA ESPECIFICACION DE LENGUAJE DE PROGRAMACION PUBLICADO
POR ECMA INTERNATIONAL.
EN LA ESPECIFICACION ECMA-262 Y LA ISO/IEC 16262.

DEFINE UN LENGUAJE DE TIPOS DINAMICOS LIGERAMENTE INSPIRADO
EN JAVA Y OTROS LENGUAJES DEL ESTILO C.
TIENE CARACTERISTICAS DE PROGRAMACION ORIENTADA A OBJETOS
MEDIANTE OBJETOS BASADOS EN PROTOTIPOS Y EN PSEUDOCLASES

ECMASCRIPT V6 ES EL ESTANDAR QUE SEGUIRA JAVASCRIPT A PARTIR
DE JUNIO DE 2015.
HASTA EL MOMENTO LA VERSION DE JS QUE ESTAMOS USANDO EN NUESTROS
NAVEGADORES Y NODEJS ES LA V5.

TIENE NUEVAS CARACTERISTICAS Y SINTAXIS DEL LENGUAJE JAVASCRIPT PARA VOLVERLO
MAS LIMPIO, ORGANIZADO Y REUTILIZABLE.

//MOTOR JAVASCRIPT V8

V8 ES UN MOTOR DE CODIGO ABIERTO PARA JAVASCRIPT
CREADO POR GOOGLE.
ESTA ESCRITO EN C++ Y ES USADO EN GOOGLE CHROME Y ESTA INTEGRADO
TAMBIEN EN EL SISTEMA OPERATIVO ANDROID 2.2 FROYO
IMPLEMENTA ECMASCRIPT COMO ESPECIFICACION - ECMA-262 V5.

V8 PUEDE FUNCIONAR DE MANERA INDIVIDUAL (STANDALONE) O
INCORPORA A CUALQUIER APLICACION C++.

//SPIDERMONKEY --------->> MOZILLA FIREFOX
//CHAKRA       --------->> INTERNET EXPLORER

//NODEJS

ES UN ENTORNO DE PROGRAMACION EN LA CAPA DEL SERVIDOR
(PERO NO LIMITANDOSE A ELLO).
ESTA BASADO EN EL LENGUAJE DE PROGRAMACION ECMASCRIPT, ASINCRONO
CON I/O DE DATOS EN UNA ARQUITECTURA ORIENTADA A EVENTOS Y BASADO
EN EL MOTOR V8 DE GOOGLE.
FUE CREADO CON EL ENFOQUE DE SER UTIL EN LA CREACION DE PROGRAMAS
DE RED ALTAMENTE ESCALABLES, COMO POR EJEMPLO SERVIDORES WEB.


//PROGRAMACION ORIENTADA A EVENTOS

ES UN PARADIGMA DE PROGRAMACION EN EL QUE TANTO LA ESTRUCTURA COMO LA EJECUCION
DE LOS PROGRAMAS VAN DETERMINADOS POR LOS SUCESOS QUE OCURRAN EN EL SISTEMA,
DEFINIDOS POR EL USUARIO O QUE ELLOS MISMOS PROVOQUEN.

//CURL

CURL IS A COMMAND LINE TOOL AND LIBRARY FOR TRANSFERRING DATA WITH URL SYNTAX,
SUPPORTING DCT, FILE, FTP, FTPS, IMAP, IMAPS, LDAP, LDAPS, SMB, SMTP, SMTPS, etc.

*/
